//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Weblitz.Mvc.Forum.Db
{
    public partial class Forum
    {
        #region Primitive Properties
    
        public int Id
        {
            get;
            set;
        }
    
        public string Name
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public ICollection<Topic> Topics
        {
            get
            {
                if (_topics == null)
                {
                    var newCollection = new FixupCollection<Topic>();
                    newCollection.CollectionChanged += FixupTopics;
                    _topics = newCollection;
                }
                return _topics;
            }
            set
            {
                if (!ReferenceEquals(_topics, value))
                {
                    var previousValue = _topics as FixupCollection<Topic>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupTopics;
                    }
                    _topics = value;
                    var newValue = value as FixupCollection<Topic>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupTopics;
                    }
                }
            }
        }
        private ICollection<Topic> _topics;

        #endregion
        #region Association Fixup
    
        private void FixupTopics(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Topic item in e.NewItems)
                {
                    item.Forum = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Topic item in e.OldItems)
                {
                    if (ReferenceEquals(item.Forum, this))
                    {
                        item.Forum = null;
                    }
                }
            }
        }

        #endregion
    }
}
