//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Weblitz.Mvc.Forum.Db
{
    public partial class Post
    {
        #region Primitive Properties
    
        public int Id
        {
            get;
            set;
        }
    
        public int TopicId
        {
            get { return _topicId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_topicId != value)
                    {
                        if (Topic != null && Topic.Id != value)
                        {
                            Topic = null;
                        }
                        _topicId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private int _topicId;
    
        public Nullable<int> ParentId
        {
            get { return _parentId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_parentId != value)
                    {
                        if (Parent != null && Parent.Id != value)
                        {
                            Parent = null;
                        }
                        _parentId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _parentId;
    
        public string Body
        {
            get;
            set;
        }
    
        public string Author
        {
            get;
            set;
        }
    
        public System.DateTime PublishedDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public ICollection<Post> Children
        {
            get
            {
                if (_children == null)
                {
                    var newCollection = new FixupCollection<Post>();
                    newCollection.CollectionChanged += FixupChildren;
                    _children = newCollection;
                }
                return _children;
            }
            set
            {
                if (!ReferenceEquals(_children, value))
                {
                    var previousValue = _children as FixupCollection<Post>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupChildren;
                    }
                    _children = value;
                    var newValue = value as FixupCollection<Post>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupChildren;
                    }
                }
            }
        }
        private ICollection<Post> _children;
    
        public Post Parent
        {
            get { return _parent; }
            set
            {
                if (!ReferenceEquals(_parent, value))
                {
                    var previousValue = _parent;
                    _parent = value;
                    FixupParent(previousValue);
                }
            }
        }
        private Post _parent;
    
        public Topic Topic
        {
            get { return _topic; }
            set
            {
                if (!ReferenceEquals(_topic, value))
                {
                    var previousValue = _topic;
                    _topic = value;
                    FixupTopic(previousValue);
                }
            }
        }
        private Topic _topic;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupParent(Post previousValue)
        {
            if (previousValue != null && previousValue.Children.Contains(this))
            {
                previousValue.Children.Remove(this);
            }
    
            if (Parent != null)
            {
                if (!Parent.Children.Contains(this))
                {
                    Parent.Children.Add(this);
                }
                if (ParentId != Parent.Id)
                {
                    ParentId = Parent.Id;
                }
            }
            else if (!_settingFK)
            {
                ParentId = null;
            }
        }
    
        private void FixupTopic(Topic previousValue)
        {
            if (previousValue != null && previousValue.Posts.Contains(this))
            {
                previousValue.Posts.Remove(this);
            }
    
            if (Topic != null)
            {
                if (!Topic.Posts.Contains(this))
                {
                    Topic.Posts.Add(this);
                }
                if (TopicId != Topic.Id)
                {
                    TopicId = Topic.Id;
                }
            }
        }
    
        private void FixupChildren(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Post item in e.NewItems)
                {
                    item.Parent = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Post item in e.OldItems)
                {
                    if (ReferenceEquals(item.Parent, this))
                    {
                        item.Parent = null;
                    }
                }
            }
        }

        #endregion
    }
}
