//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Weblitz.Mvc.Forum.Db
{
    public partial class Topic
    {
        #region Primitive Properties
    
        public int Id
        {
            get;
            set;
        }
    
        public int ForumId
        {
            get { return _forumId; }
            set
            {
                if (_forumId != value)
                {
                    if (Forum != null && Forum.Id != value)
                    {
                        Forum = null;
                    }
                    _forumId = value;
                }
            }
        }
        private int _forumId;
    
        public string Title
        {
            get;
            set;
        }
    
        public string Body
        {
            get;
            set;
        }
    
        public string Author
        {
            get;
            set;
        }
    
        public System.DateTime PublishedDate
        {
            get;
            set;
        }
    
        public bool Sticky
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public Forum Forum
        {
            get { return _forum; }
            set
            {
                if (!ReferenceEquals(_forum, value))
                {
                    var previousValue = _forum;
                    _forum = value;
                    FixupForum(previousValue);
                }
            }
        }
        private Forum _forum;
    
        public ICollection<Post> Posts
        {
            get
            {
                if (_posts == null)
                {
                    var newCollection = new FixupCollection<Post>();
                    newCollection.CollectionChanged += FixupPosts;
                    _posts = newCollection;
                }
                return _posts;
            }
            set
            {
                if (!ReferenceEquals(_posts, value))
                {
                    var previousValue = _posts as FixupCollection<Post>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupPosts;
                    }
                    _posts = value;
                    var newValue = value as FixupCollection<Post>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupPosts;
                    }
                }
            }
        }
        private ICollection<Post> _posts;

        #endregion
        #region Association Fixup
    
        private void FixupForum(Forum previousValue)
        {
            if (previousValue != null && previousValue.Topics.Contains(this))
            {
                previousValue.Topics.Remove(this);
            }
    
            if (Forum != null)
            {
                if (!Forum.Topics.Contains(this))
                {
                    Forum.Topics.Add(this);
                }
                if (ForumId != Forum.Id)
                {
                    ForumId = Forum.Id;
                }
            }
        }
    
        private void FixupPosts(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Post item in e.NewItems)
                {
                    item.Topic = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Post item in e.OldItems)
                {
                    if (ReferenceEquals(item.Topic, this))
                    {
                        item.Topic = null;
                    }
                }
            }
        }

        #endregion
    }
}
